version: '3.7'

services:

  react-ui:
    build:
      context: ./react_app
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./react_app:/app/react_app
       - /app/react_app/node_modules